[package]
name = "rsort"
version = "0.1.0"
authors = ["XiaochenCui <jcnlcxc.new@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rand = "0.8.3"
procinfo = "0.4.2"